baseURL = "/"
languageCode = "en-gb"
DefaultContentLanguage = "en"

title = "Gibbon Documentation"
theme = "docdock"
themesdir = "themes"
enableGitInfo = true

[params]
ghRepo = "https://github.com/GibbonEdu/docs/"
editURL = "https://github.com/GibbonEdu/docs/edit/master/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
highlightStyle = "atom-one-dark"
themeStyle = "theme" # overide base css
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title" | "weight"
pluralizelisttitles = false
[outputs]
home = [ "HTML", "RSS", "JSON"]



[[menu.shortcuts]]
pre = "<h3>Links</h3>"
name = "<i class='fa fa-fw fa-home'></i> Gibbon Website"
url = "https://gibbonedu.org"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-fw fa-comments-o'></i> Support Forum"
url = "https://ask.gibbonedu.org"
weight = 20

[[menu.shortcuts]]

name = "<i class='fa fa-fw fa-github'></i> GibbonEdu/core"
identifier = "ds"
url = "https://github.com/GibbonEdu/core/"
weight = 30

[[menu.shortcuts]]
name = "<i class='fa fa-fw fa-github'></i> GibbonEdu/docs"
url = "https://github.com/GibbonEdu/docs/"
weight = 40
